### ISSUE TITLE
Accuracy in README seems inaccurate.

### ISSUE THREAD

**Issue by your-diary** [tna0y/Python-random-module-cracker#5]
According to the `README.md`,

> ## Accuracy
> 
> Cracker is not absolutely accurate. It is able to perform close to **100%** accurate on first **624** 32-bit generations, **~99.5%** on the first **1 000**, **~95%** on the first **10 000** and then figures drop to **~50%** accurate to generation **50 000**.

but I think this is the value of total (or accumulated) accuracy.

When I plot the accuracy of recent 100 predictions, the plot drops much faster than the total accuracy. And IMHO this is a more appropriate measure when discussing prediction accuracy.

![a](https://user-images.githubusercontent.com/58146437/125150705-e4750280-e17c-11eb-8ab8-316fe88c355e.png)

Though I do ***not*** think what is written in `README.md` is wrong, I think it is a bit confusive.

**Comment by tna0y** [comment]
The issue has been fixed in the latest update thanks to @mcfx
